title: Nimbus
description: >-
  Open source cloud replacement for vacuum robots enabling local-only operation
baseurl: ""
url: https://nimbus.cleaning
github_username: NimbusVacuum

plugins:
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
