name: Autocloser
on: [pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose all PRs
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "@${issue.user.login} this PR was automatically closed because this repository is not intended for any external use or contribution."
        issue-pattern: ".*"
