# Very similar to the release build.
{
  'name': 'Nightly build',
  'on': {
    'schedule': [
      {
        'cron': '0 2 * * *'
      }
    ],
    'workflow_dispatch': null
  },
  'jobs':
    {
      'nightly_build':
        {
          'runs-on': 'ubuntu-latest',
          'steps':
            [
              { 
                'uses': 'actions/checkout@v3',
                'with': {
                  'fetch-depth': 0
                }
              },
              {
                'name': 'Use Node.js 18.x',
                'uses': 'actions/setup-node@v3',
                'with': { 'node-version': '18.x' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Nimbus frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Nimbus',
                'run': 'npm run build --workspace=backend',
              },
              {
                'name': 'UPX-compress nimbus binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Generate changelog',
                'run': 'npm run generate_nightly_changelog',
              },
              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest nightly',
              },
              {
                'name': 'Import GPG key',
                'id': 'import_gpg',
                'uses': 'crazy-max/ghaction-import-gpg@v5',
                'with': {
                  'gpg_private_key': '${{ secrets.GPG_PRIVATE_KEY }}',
                  'passphrase': '${{ secrets.GPG_PASSPHRASE }}'
                }
              },
              {
                'name': 'Push binaries to nightly repo',
                'id': 'push_directory',
                'uses': 'NimbusVacuum/github-action-push-to-another-repository@v2',
                'env': {
                  'API_TOKEN_GITHUB': '${{ secrets.API_TOKEN_GITHUB }}'
                },
                'with': {
                  'source-directory': 'build',
                  'destination-github-username': 'NimbusVacBot',
                  'destination-repository-name': 'nimbus-nightly-builds',
                  'destination-repository-username': 'NimbusVacuum',
                  'user-email': '120611326+NimbusVacBot@users.noreply.github.com',
                  'target-branch': 'main',
                  'gpg-fingerprint': '${{ steps.import_gpg.outputs.fingerprint }}'
                }
              }
            ],
        },
    },
}
