{
  'name': 'Release',
  'on': { 'release': { 'types': ['published'] } },
  'jobs':
    {
      'publish-release':
        {
          'runs-on': 'ubuntu-latest',
          'strategy': { 'matrix': { 'node-version': ['16.x'] } },
          'steps':
            [
              { 'uses': 'actions/checkout@v2' },
              {
                'name': 'Use Node.js ${{ matrix.node-version }}',
                'uses': 'actions/setup-node@v3',
                'with': { 'node-version': '${{ matrix.node-version }}' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Nimbus frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Nimbus armv7',
                'run': 'npm run build_armv7 --workspace=backend',
              },
              {
                'name': 'Build Nimbus armv7 lowmem',
                'run': 'npm run build_armv7_lowmem --workspace=backend',
              },
              {
                'name': 'Build Nimbus aarch64',
                'run': 'npm run build_aarch64 --workspace=backend',
              },

              {
                'name': 'Upload Nimbus armv7',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/armv7/nimbus',
                    'asset_name': 'nimbus-armv7',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },
              {
                'name': 'Upload Nimbus armv7 lowmem',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/armv7/nimbus-lowmem',
                    'asset_name': 'nimbus-armv7-lowmem',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },
              {
                'name': 'Upload Nimbus aarch64',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/aarch64/nimbus',
                    'asset_name': 'nimbus-aarch64',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },

              {
                'name': 'UPX-compress nimbus binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Upload Nimbus armv7.upx',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/armv7/nimbus.upx',
                    'asset_name': 'nimbus-armv7.upx',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },
              {
                'name': 'Upload Nimbus armv7 lowmem.upx',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/armv7/nimbus-lowmem.upx',
                    'asset_name': 'nimbus-armv7-lowmem.upx',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },
              {
                'name': 'Upload Nimbus aarch64.upx',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/aarch64/nimbus.upx',
                    'asset_name': 'nimbus-aarch64.upx',
                    'asset_content_type': 'binary/octet-stream',
                  },
              },

              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest',
              },
              {
                'name': 'Upload manifest',
                'uses': 'actions/upload-release-asset@v1.0.2',
                'env': { 'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}' },
                'with':
                  {
                    'upload_url': '${{ github.event.release.upload_url }}',
                    'asset_path': './build/nimbus_release_manifest.json',
                    'asset_name': 'nimbus_release_manifest.json',
                    'asset_content_type': 'application/json',
                  },
              },
            ],
        },
    },
}
